//Songs
export const RECEIVE_ALL_SONGS = "RECEIVE_ALL_SONGS";
export const RECEIVE_ALL_COMMENTS = "RECEIVE_ALL_COMMENTS";
export const RECEIVE_ALL_SONGS_FOR_GENRE = "RECEIVE_ALL_SONGS_FOR_GENRE";

//Favorites
export const RECEIVE_ALL_FAVORITES_FOR_USER = "RECEIVE_ALL_FAVORITES_FOR_USER";
// export const DYNAMIC_RECEIVE_ALL_FAVORITES_FOR_USER =
//   "DYNAMIC_RECEIVE_ALL_FAVORITES_FOR_USER";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const RECEIVE_ALL_FAVORITES_ALL_DETAILS_FOR_USER =
  "RECEIVE_ALL_FAVORITES_ALL_DETAILS_FOR_USER";

//Genres
export const RECEIVE_ALL_GENRES = "RECEIVE_ALL_GENRES";

//Profile
export const RECEIVE_ALL_SONGS_POSTED_BY_USER =
  "RECEIVE_ALL_SONGS_POSTED_BY_USER";

export const DYNAMIC_RECEIVE_ALL_SONGS_POSTED_BY_USER =
  "DYNAMIC_RECEIVE_ALL_SONGS_POSTED_BY_USER";

export const RECEIVE_PROFILE_VIEW_FOR_POSTED =
  "RECEIVE_PROFILE_VIEW_FOR_POSTED";

export const RECEIVE_ALL_USERS = "RECEIVE_ALL_USERS";
