//Songs
export const RECEIVE_ALL_SONGS = "RECEIVE_ALL_SONGS";

//Favorites
export const RECEIVE_ALL_FAVORITES_FOR_USER = "RECEIVE_ALL_FAVORITES_FOR_USER";
// export const DELETE_FAVORITE = "DELETE_FAVORITE";
// export const ADD_FAVORITE = "ADD_FAVORITE";
